language: python
python:
  - "2.7"
sudo:
  - required
before_install:
  - pip install pep8
install:
  - sudo python setup.py install
script:
  # Run pep8 on all .py files in all subfolders
  # (Ignore "E402: module level import not at top of file"
  # because of use case sys.path.append('..'); import <module>)
  # E501 : line too long (max 79 characters)
  - find . -name \*.py -exec pep8 --ignore=E402,E501 {} +
